# Generated by Django 4.2.7 on 2025-12-03 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerprintDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Device name/identifier', max_length=100)),
                ('model', models.CharField(choices=[('ZK702', 'ZKteco Model 702')], default='ZK702', max_length=50)),
                ('ip_address', models.GenericIPAddressField(help_text='Device IP address')),
                ('port', models.IntegerField(default=4370, help_text='Device port (default: 4370)')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('grade_category', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('HIGH_SCHOOL', 'High School'), ('KINDERGARTEN', 'Kindergarten')], help_text='Grade category this device is assigned to (one device per grade)', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance')], default='ACTIVE', max_length=20)),
                ('last_sync', models.DateTimeField(blank=True, help_text='Last synchronization time', null=True)),
                ('is_connected', models.BooleanField(default=False, help_text='Current connection status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fingerprint Device',
                'verbose_name_plural': 'Fingerprint Devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out')], max_length=10)),
                ('timestamp', models.DateTimeField(help_text='Attendance timestamp from device')),
                ('fingerprint_id', models.IntegerField(help_text='Fingerprint ID from device')),
                ('device_serial', models.CharField(blank=True, help_text='Device serial number', max_length=100, null=True)),
                ('is_synced', models.BooleanField(default=False, help_text='Whether this record was synced from device')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, help_text='Device that recorded this attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='attendance.fingerprintdevice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.student')),
            ],
            options={
                'verbose_name_plural': 'Attendances',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['student', 'timestamp'], name='attendance__student_6bd6d0_idx'), models.Index(fields=['timestamp'], name='attendance__timesta_6c8532_idx'), models.Index(fields=['attendance_type', 'timestamp'], name='attendance__attenda_c0ccbd_idx')],
            },
        ),
    ]
