# Generated by Django 4.2.7 on 2025-12-15 15:11

from django.db import migrations, models
import django.db.models.deletion


def assign_devices_to_default_branch(apps, schema_editor):
    """Assign all existing devices to the default branch (Main Branch)"""
    branch_model = apps.get_model('core', 'Branch')
    device_model = apps.get_model('attendance', 'FingerprintDevice')
    
    # Get the default branch (should exist from previous migration)
    try:
        default_branch = branch_model.objects.get(id=1)
        # Assign all devices without a branch to the default branch
        device_model.objects.filter(branch__isnull=True).update(branch=default_branch)
    except branch_model.DoesNotExist:
        # If default branch doesn't exist, create it
        default_branch = branch_model.objects.create(
            id=1,
            name='Main Branch',
            address='Default branch for existing devices'
        )
        device_model.objects.filter(branch__isnull=True).update(branch=default_branch)


def reverse_migration(apps, schema_editor):
    """Reverse migration - nothing to do"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_branch_student_branch'),
        ('attendance', '0002_remove_fingerprint_id_and_device_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprintdevice',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this device belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.branch'),
        ),
        migrations.RunPython(assign_devices_to_default_branch, reverse_migration),
        migrations.AlterField(
            model_name='fingerprintdevice',
            name='branch',
            field=models.ForeignKey(help_text='Branch this device belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.branch'),
        ),
        migrations.AlterField(
            model_name='fingerprintdevice',
            name='grade_category',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('HIGH_SCHOOL', 'High School'), ('KINDERGARTEN', 'Kindergarten')], help_text='Grade category this device is assigned to (one device per grade per branch)', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='fingerprintdevice',
            unique_together={('branch', 'grade_category')},
        ),
    ]
