# Generated by Django 4.2.7 on 2025-12-22 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_level'),
        ('attendance', '0003_fingerprintdevice_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Phone number SMS was sent to', max_length=20)),
                ('message', models.TextField(help_text='SMS message content')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('RECEIVED', 'Received')], default='PENDING', max_length=20)),
                ('api_response', models.JSONField(blank=True, help_text='Raw API response from SMS provider', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if SMS failed')),
                ('message_id', models.CharField(blank=True, help_text='Message ID from SMS provider', max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When SMS was sent', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When SMS was delivered', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='attendance.attendance')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='core.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='core.student')),
            ],
            options={
                'verbose_name': 'SMS Log',
                'verbose_name_plural': 'SMS Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'created_at'], name='attendance__student_cba1a0_idx'), models.Index(fields=['status', 'created_at'], name='attendance__status_eba78e_idx'), models.Index(fields=['attendance'], name='attendance__attenda_1e4279_idx')],
            },
        ),
    ]
