# Generated by Django 4.2.7 on 2026-01-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_smslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_start_time', models.TimeField(help_text='Start time for attendance window (e.g., 08:00)')),
                ('attendance_end_time', models.TimeField(help_text='End time for attendance window (e.g., 08:30)')),
                ('lateness_start_time', models.TimeField(help_text='Start time for lateness window (e.g., 08:30)')),
                ('lateness_end_time', models.TimeField(help_text='End time for lateness window (e.g., 08:40)')),
                ('sms_template', models.TextField(default='Qurtubah School\n\nHello {parent_name}, Your child {student_name} has checked in at {time_attended}.\n\nThank you for your attention.', help_text='SMS message template. Available variables: {parent_name}, {student_name}, {time_attended}')),
                ('sync_frequency_hours', models.IntegerField(default=0, help_text='Hours component of sync frequency')),
                ('sync_frequency_minutes', models.IntegerField(default=0, help_text='Minutes component of sync frequency')),
                ('sync_frequency_seconds', models.IntegerField(default=30, help_text='Seconds component of sync frequency')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Settings',
                'verbose_name_plural': 'Attendance Settings',
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('ATTENDED', 'Attended'), ('LATE', 'Late'), ('ABSENT', 'Absent')], help_text='Attendance status: Attended, Late, or Absent', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
