# Generated by Django 4.2.7 on 2026-01-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_add_attendance_settings_and_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprintdevice',
            name='grade_category',
            field=models.CharField(help_text='Grade category this device is assigned to (one device per grade per branch)', max_length=50),
        ),
    ]
