# Generated by Django 4.2.7 on 2026-01-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_fingerprintdevice_grade_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fingerprintdevice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fingerprintdevice',
            name='levels',
            field=models.JSONField(default=list, help_text='List of student levels this device is assigned to (e.g., [1, 2, 3] or [1])'),
        ),
        migrations.AlterField(
            model_name='fingerprintdevice',
            name='grade_category',
            field=models.CharField(help_text='Grade category this device is assigned to', max_length=50),
        ),
        migrations.AlterField(
            model_name='fingerprintdevice',
            name='model',
            field=models.CharField(help_text='Device model (e.g., ZK702)', max_length=100),
        ),
    ]
