# Generated by Django 4.2.7 on 2026-05-19 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_fingerprintdevice_adms_send_utc_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fingerprintdevice',
            name='adms_send_utc_time',
        ),
    ]
