# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_remove_fingerprintdevice_adms_send_utc_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesettings',
            name='adms_ahead_serial_numbers',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Internal storage: one device serial number (SN) per line. Managed via admin device picker.',
            ),
        ),
        migrations.AddField(
            model_name='attendancesettings',
            name='adms_ahead_offset_hours',
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text='Hours to subtract from ADMS punch times for devices listed above (e.g. 5 if clock is 5h ahead).',
            ),
        ),
    ]
