# Generated by Django 4.2.7 on 2025-12-15 15:11

from django.db import migrations, models
import django.db.models.deletion


def create_default_branch_and_assign_students(apps, schema_editor):
    """Create a default branch and assign all existing students to it"""
    branch_model = apps.get_model('core', 'Branch')
    student_model = apps.get_model('core', 'Student')
    
    # Create default branch if it doesn't exist
    default_branch, _ = branch_model.objects.get_or_create(
        id=1,
        defaults={
            'name': 'Main Branch',
            'address': 'Default branch for existing students'
        }
    )
    
    # Assign all students without a branch to the default branch
    student_model.objects.filter(branch__isnull=True).update(branch=default_branch)


def reverse_migration(apps, schema_editor):
    """Reverse migration - nothing to do"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_student_fingerprint_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Branch name', max_length=200)),
                ('address', models.TextField(help_text='Branch address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this student belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.branch'),
        ),
        migrations.RunPython(create_default_branch_and_assign_students, reverse_migration),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(help_text='Branch this student belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.branch'),
        ),
    ]
