# Generated by Django 4.2.7 on 2026-01-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(blank=True, help_text='Class identifier (e.g., A, B, 1, 2)', max_length=2),
        ),
    ]
