# Generated by Django 4.2.7 on 2026-01-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_class_name_to_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('KINDERGARTEN', 'Kindergarten'), ('PRIMARY', 'Primary'), ('INTERMEDIATE', 'Intermediate'), ('SECONDARY', 'Secondary'), ('AMERICAN_DIPLOMA', 'American Diploma')], max_length=20),
        ),
    ]
